// Try - Catch

const numero1 = 10;
const numero3 = 15;

console.log(numero1);

try { //Try intentara hacer algo
    console.log(numero2);
} catch (error) { //Si no caera en el catch
    console.log(error)
}

console.log(numero3);